### ISSUE TITLE
Uncaught TypeError: $(...).on is not a function

### ISSUE THREAD

**Issue by balawton** [protonet/jquery.inview#55]
I get the above error when I try and open the example files

**Comment by andypillip** [comment]
Are you using jQuery? In which Version?

If you're using jQuery, are you using another library that might bind to `$`?

**Comment by brendanlawton** [comment]
Hi Andy, I haven't changed any of the files, just downloading and then opening the examples.

**Comment by andypillip** [comment]
You downloaded the repository from github and opened the html files in /example?

I checked those, none of them is calling `.on()`.

As they use old jQuery, they use the `.bind()` and `.live()` functions.

**Comment by Gnomal** [comment]
Hey Andy,

Just download the files and opened the examples, nothing works and have this issue  Uncaught TypeError: $(...).on is not a function (jquery 1.4.4). Same issue with jquery 2.0.0. Using FF 50.1.0 And Chrome 55.0.2883.87 m (64-bit). Thank you

**Comment by andypillip** [comment]
@Gnomal again, please tell me *where* you downloaded these files!

**Comment by Gnomal** [comment]
@andypillip https://github.com/protonet/jquery.inview Here :) Once one by one, once by ZIP

**Comment by andypillip** [comment]
@Gnomal it's that the example files are broken.

According to the README jquery.inview requires jQuery ≥ 1.8, while the example filese still reference 1.4.

As a workaround you can alter the example files and use an up-to-date jQuery.

F.e. in _advanced.html_, replace the line 

```html
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
```

with

```html
<script src="https://code.jquery.com/jquery-1.8.0.min.js"></script>
```

The [method `bind()` got deprecated only in 3.0](http://api.jquery.com/category/deprecated/deprecated-3.0/), so the examples should work with jQuery < 3.0.

**Comment by naserinassab** [comment]
thank you

**Comment by bhanupsc** [comment]
var jqueryObj = $;
use jqueryObj in place of $

**Comment by romuye123** [comment]
Downloaded this template:
https://colorlib.com/download/132/

Works fine on localhost. But get following error on my cloud server:

Uncaught TypeError: $(...).easyResponsiveTabs is not a function
    at responsiveTabs (main.js:168)
    at HTMLDocument.<anonymous> (main.js:398)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.J (jquery.min.js:2)
NOTE: This error is appearing on MAC Chrome browser. Working fine on other browsers.

**Comment by pavanvarmab** [comment]
if not the jquery version error once clear the catch of your browser because of the Jquery files already present in the cache it will cause the problem

**Comment by onewheelash** [comment]
> if not the jquery version error once clear the catch of your browser because of the Jquery files already present in the cache it will cause the problem

Thanks for the tip.  Clearing my cache got took care of the Uncaught TypeError: $(...) console error.

**Comment by CristianAlvG** [comment]
I could solve the problem, i had installed bootstrap with JQuery and his library was changing my js and the way it works, so i decided to delete the JQuery Bootstrap href and it solves my problems thanks to andyphillip

**Comment by VijayGawade** [comment]
use 'jQuery' instead of '$'.
thats work for me

**Comment by mh27588** [comment]
> I could solve the problem, i had installed bootstrap with JQuery and his library was changing my js and the way it works, so i decided to delete the JQuery Bootstrap href and it solves my problems thanks to andyphillip

This was absolutely the issue for me as well, 2 years on!  Thank you @CristianAlvG
